trigger:
- master

variables:
  tag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Logga in till ACR och bygg & pusha via Docker Compose
          - task: DockerCompose@1
            displayName: 'Login to ACR and Build & Push'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'ACR-lcp'  # Din Azure service connection
              azureContainerRegistry: 'lcslsdcontainer'
              dockerComposeFile: 'ci/docker-compose-azure.yaml'
              action: 'Push services'
              projectName: 'mtmse-readium-lcp-server'
              qualifyImageNames: true


  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'developmentlcp'  # Eller skapa ett nytt miljö om nödvändigt
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Steg 1: Logga in till Azure (valfritt, användbart för ytterligare konfiguration)
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Om du behöver, logga in till Azure
                      az account show

                # Steg 3: Deploy Docker Compose till Azure App Service
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Compose to Azure Web App'
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    appName: 'LSDLCDserver'  # Din Azure Web App
                    appSettings:
                      -DOCKER_REGISTRY_SERVER_USERNAME lcslsdcontainer
                      -DOCKER_REGISTRY_SERVER_URL lcslsdcontainer.azurecr.io
                      -DOCKER_REGISTRY_SERVER_PASSWORD $(RegistrySecret)
                    containers: |
                      lcslsdcontainer.azurecr.io/lcpserver:latest
                      lcslsdcontainer.azurecr.io/lsdserver:latest
                    multicontainerConfigFile: 'ci/docker-compose-azure.yaml'  # Ange rätt sökväg till docker-compose.yml
