trigger:
- master

variables:
  resourceGroup: 'mtm_lcp-and-lsp-servers_prod'
  appName: 'LSDLCDserver'
  acrName: 'lcslsdcontainer'
  dockerComposeFile: 'ci/docker-compose.yaml'  # Path to your docker-compose file
  azureComposeFile: 'ci/docker-compose-azure.yaml'  # Path to your Azure-specific compose file
  containerRegistry: 'docker_lcp'  # Azure service connection
  registryUrl: 'lcslsdcontainer.azurecr.io'

stages:
  - stage: BuildAndPush
    displayName: Build and Push with Docker Compose
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Log in to Azure Container Registry
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: $(containerRegistry)

          # Build and Push using Docker Compose
          - script: |
              docker-compose -f $(dockerComposeFile) build
              docker-compose -f $(dockerComposeFile) push
            displayName: 'Build and Push Docker Compose Images'

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: BuildAndPush
    jobs:
      - deployment: Deploy
        displayName: Deploy with Docker Compose
        environment: 'developmentlcp'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Deploy Docker Compose to Azure
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Compose to Azure'
                  inputs:
                    azureSubscription: $(containerRegistry)
                    appName: $(appName)
                    multicontainerConfigFile: $(azureComposeFile)
                    appSettings:
                      -DOCKER_REGISTRY_SERVER_URL=$(registryUrl)
                      -DOCKER_REGISTRY_SERVER_USERNAME=$(acrName)
                      -DOCKER_REGISTRY_SERVER_PASSWORD=$(RegistrySecret)