trigger:
- ci

variables:
  tag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: 'docker_lcp'  # Namnet på din service connection

          - task: Docker@2
            displayName: Build and Push lcpserver
            inputs:
              command: buildAndPush
              repository: 'lcslsdcontainer.azurecr.io/lcpserver'
              dockerfile: 'ci/Dockerfile'
              tags: |
                $(tag)
              buildContext: .
              target: 'runtime-lcp'

          - task: Docker@2
            displayName: Build and Push lsdserver
            inputs:
              command: buildAndPush
              repository: 'lcslsdcontainer.azurecr.io/lsdserver'
              dockerfile: 'ci/Dockerfile'
              tags: |
                $(tag)
              buildContext: .
              target: 'runtime-lsd'