trigger:
- master

variables:
  tag: $(Build.BuildId)
  resourceGroup: 'mtm_lcp-and-lsp-servers_prod'  # Byt ut med ditt resursgruppnamn
  appName: 'LSDLCDserver'
  acrName: 'lcslsdcontainer'  # Din ACR-namn

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Logga in till ACR
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: 'docker_lcp'  # Din Azure service connection

        # Bygg och pusha nginx-bilden
          - task: Docker@2
            displayName: 'Build and Push nginx image'
            inputs:
              containerRegistry: 'docker_lcp'
              repository: 'nginx'
              command: 'buildAndPush'
              Dockerfile: 'ci/nginx/Dockerfile'
              tags: 'latest'

          # Bygg och pusha övriga tjänster via Docker Compose
          - task: DockerCompose@1
            displayName: 'Build & Push Services'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'acr-lcp'
              azureContainerRegistry: '$(acrName)'
              dockerComposeFile: 'ci/docker-compose-azure.yaml'
              action: 'Push services'
              projectName: 'mtmse-readium-lcp-server'  # Giltigt projekt namn utan snedstreck
              qualifyImageNames: true


  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'developmentlcp'  # Eller skapa ett nytt miljö om nödvändigt
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Steg 1: Logga in till Azure (valfritt, användbart för ytterligare konfiguration)
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Om du behöver, logga in till Azure
                      az account show

                # Steg 3: Deploy Docker Compose till Azure App Service
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Compose to Azure Web App'
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    appName: 'LSDLCDserver'  # Din Azure Web App
                    appSettings:
                      -DOCKER_REGISTRY_SERVER_USERNAME lcslsdcontainer
                      -DOCKER_REGISTRY_SERVER_URL lcslsdcontainer.azurecr.io
                      -DOCKER_REGISTRY_SERVER_PASSWORD $(RegistrySecret)
                    containers: |
                      lcslsdcontainer.azurecr.io/lcpserver:latest
                      lcslsdcontainer.azurecr.io/lsdserver:latest
                    multicontainerConfigFile: 'ci/docker-compose-azure.yaml'  # Ange rätt sökväg till docker-compose.yml
