trigger:
- master

variables:
  resourceGroup: 'lcp_dev'
  appName: 'LSDLCDserver'
  acrName: 'lcslsdcontainer'
  dockerComposeFile: 'ci/docker-compose.yaml'  # Path to your docker-compose file
  azureComposeFile: 'ci/docker-compose-azure.yaml'  # Path to your Azure-specific compose file
  containerRegistry: 'docker_lcp'  # Azure service connection
  registryUrl: 'lcslsdcontainer.azurecr.io'

stages:
  - stage: BuildAndPush
    displayName: Build and Push with Docker Compose
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          - script: |
              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version
            displayName: 'Install Docker Compose'

          # Log in to Azure Container Registry
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: $(containerRegistry)

          # Build and Push using Docker Compose
          - script: |
              docker-compose -f $(dockerComposeFile) build
              docker-compose -f $(dockerComposeFile) push
            displayName: 'Build and Push Docker Compose Images'

  - stage: Deploy
    displayName: Deploy to Azure Web App
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: Deploy Docker Compose App
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Login to Azure using AzureCLI
          - task: AzureCLI@2
            displayName: 'Login to Azure'
            inputs:
              azureSubscription: 'ACR-lcp'  # Azure service connection of type AzureRM
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account show

          # Deploy the Docker Compose file
          - task: AzureCLI@2
            displayName: 'Deploy Docker Compose to Azure'
            inputs:
              azureSubscription: 'ACR-lcp'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp config container set \
                  --name $(appName) \
                  --resource-group $(resourceGroup) \
                  --multicontainer-config-type compose \
                  --multicontainer-config-file $(System.DefaultWorkingDirectory)/$(azureComposeFile)