trigger:
- master

variables:
  tag: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Steg 1: Lista filer för felsökning
          - script: ls -R /home/vsts/work/1/s/
            displayName: 'List files in source directory'

          # Steg 2: Logga in till ACR via Docker Registry service connection
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: 'docker_lcp'  # Namnet på din Docker Registry service connection

          # Steg 3: Bygg och pusha lcpserver-bild
          - task: Docker@2
            displayName: Build and Push lcpserver
            inputs:
              command: buildAndPush
              repository: 'lcslsdcontainer.azurecr.io/lcpserver'
              dockerfile: 'ci/Dockerfile'  # Direkt sökväg till Dockerfile
              tags: |
                $(tag)
              buildContext: '.'  # Kontexten till byggsteget

          # Steg 4: Bygg och pusha lsdserver-bild
          - task: Docker@2
            displayName: Build and Push lsdserver
            inputs:
              command: buildAndPush
              repository: 'lcslsdcontainer.azurecr.io/lsdserver'
              dockerfile: 'ci/Dockerfile'  # Direkt sökväg till Dockerfile
              tags: |
                $(tag)
              buildContext: '.'  # Kontexten till byggsteget

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'developmentlcp'  # Eller skapa ett nytt miljö om nödvändigt
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Steg 1: Logga in till Azure (valfritt, användbart för ytterligare konfiguration)
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Om du behöver, logga in till Azure
                      az account show

                # Steg 2: Uppdatera docker-compose-azure.yaml med rätt taggar
                - task: Bash@3
                  displayName: 'Update docker-compose-azure.yaml with tag'
                  inputs:
                    targetType: 'inline'
                    script: |
                      sed -i 's/\${TAG}/'"$(tag)"'/g' ci/docker-compose-azure.yaml

                # Steg 3: Deploy Docker Compose till Azure App Service
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Compose to Azure Web App'
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    appName: 'LSDLCDserver'  # Din Azure Web App
                    configurationFile: 'ci/docker-compose-azure.yaml'  # Ange rätt sökväg till docker-compose.yml