trigger:
- master

variables:
  tag: $(Build.BuildId)
  resourceGroup: 'mtm_lcp-and-lsp-servers_prod'  # Byt ut med ditt resursgruppnamn
  appName: 'LSDLCDserver'
  acrName: 'lcslsdcontainer'  # Din ACR-namn

stages:
  - stage: Build
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self

          # Logga in till ACR
          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: 'login'
              containerRegistry: 'docker_lcp'  # Din Azure service connection

          - task: Docker@2
            displayName: 'Bygg nginx-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'build'
              Dockerfile: 'ci/nginx/Dockerfile'
              buildContext: 'ci/'
              repository: 'nginx'
              tags: 'latest'

          # Pusha nginx-bild
          - task: Docker@2
            displayName: 'Pusha nginx-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'push'
              repository: 'nginx'
              tags: 'latest'

          - task: Docker@2
            displayName: 'Bygg lcpserver-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'build'
              Dockerfile: 'ci/Dockerfile'
              buildContext: './'
              repository: 'lcpserver'
              tags: 'latest'
              arguments: '--target runtime-lcp'

          # Pusha lcpserver-bild
          - task: Docker@2
            displayName: 'Pusha lcpserver-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'push'
              repository: 'lcpserver'
              tags: 'latest'

          # Bygg lsdserver-bild
          - task: Docker@2
            displayName: 'Bygg lsdserver-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'build'
              Dockerfile: 'ci/Dockerfile'
              buildContext: './'
              repository: 'lsdserver'
              tags: 'latest'
              arguments: '--target runtime-lsd'

          # Pusha lsdserver-bild
          - task: Docker@2
            displayName: 'Pusha lsdserver-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'push'
              repository: 'lsdserver'
              tags: 'latest'
          - task: Docker@2
            displayName: 'Bygg test-frontend-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'build'
              Dockerfile: 'ci/test-frontend/Dockerfile'
              buildContext: './ci/test-frontend'
              repository: 'test-frontend'
              tags: 'latest'
              arguments: '--target runtime-test-frontend'

          # Pusha test-frontend-bild
          - task: Docker@2
            displayName: 'Pusha test-frontend-bild'
            inputs:
              containerRegistry: 'docker_lcp'
              command: 'push'
              repository: 'test-frontend'
              tags: 'latest'
              
          # Lista Docker bilder för verifiering
          - script: docker images
            displayName: 'Lista Docker-bilder'


  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'developmentlcp'  # Eller skapa ett nytt miljö om nödvändigt
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # Steg 1: Logga in till Azure (valfritt, användbart för ytterligare konfiguration)
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Om du behöver, logga in till Azure
                      az account show

                # Steg 3: Deploy Docker Compose till Azure App Service
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Docker Compose to Azure Web App'
                  inputs:
                    azureSubscription: 'ACR-lcp'  # Din Azure service connection
                    appName: 'LSDLCDserver'  # Din Azure Web App
                    appSettings:
                      -DOCKER_REGISTRY_SERVER_USERNAME lcslsdcontainer
                      -DOCKER_REGISTRY_SERVER_URL lcslsdcontainer.azurecr.io
                      -DOCKER_REGISTRY_SERVER_PASSWORD $(RegistrySecret)
                    containers: |
                      lcslsdcontainer.azurecr.io/nginx:latest
                      lcslsdcontainer.azurecr.io/lcpserver:latest
                      lcslsdcontainer.azurecr.io/lsdserver:latest
                    multicontainerConfigFile: 'ci/docker-compose-azure.yaml'  # Ange rätt sökväg till docker-compose.yml
