{{- $lcp_hostname := regexReplaceAll "https?://" .Values.lcp.public_base_url "" -}}
{{- $lsd_hostname := regexReplaceAll "https?://" .Values.lsd.public_base_url "" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lcp
  namespace: lcp
spec:
  rules:
    - host: {{ $lcp_hostname }}
      http:
        paths:
          - backend:
              service:
                name: lcpserver
                port:
                  number: 8989
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lcp-status
  namespace: lcp
spec:
  rules:
    - host: {{ $lsd_hostname }}
      http:
        paths:
          - backend:
              service:
                name: lsdserver
                port:
                  number: 8990
            path: /
            pathType: Prefix
