apiVersion: v1
kind: Secret
metadata:
  name: lcp-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  htpasswd: {{ htpasswd .Values.auth.username .Values.auth.password }}
  config.yaml: {{ tpl (.Files.Get "config/config.yaml.tpl") . | b64enc }}
