lcp_update_auth:
    username: "admin"
    password: "Test1234"

lsd_notify_auth:
    username: "admin"
    password: "Test1234"

# LCP Server

profile: "basic"
lcp:
    host: "127.0.0.1"
    public_base_url:  "http://lcpserver:8989"
    port: 8989
    database: "mssql://server=tcp:merkur-dev-server.database.windows.net,1433;Initial Catalog=lcp_dev;Persist Security Info=False;User ID=merkur_admin;Password=GoTeam!!!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    auth_file: "/app/.htpasswd"

storage:

certificate:
    cert: "/app/cert/edrlab.crt"
    private_key: "/app/cert/edrlab.key"
license:
    links:
        status: "http://lcpserver:8990/licenses/{license_id}/status"
        hint: "https://localhost/lcp-hint"


# LSD Server

lsd:
    host: "127.0.0.1"
    public_base_url:  "http://lsdserver:8990"
    port: 8990
    database: "mssql://server=tcp:merkur-dev-server.database.windows.net,1433;Initial Catalog=lcp_dev;Persist Security Info=False;User ID=merkur_admin;Password=GoTeam!!!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    auth_file: "/app/.htpasswd"
    license_link_url: "http://lsdserver:8990/{license_id}"
license_status:
    register: true
    renew: true
    return: true
    renting_days: 30
    renew_days: 7
