services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: local/nginx:latest  # Local image name
    user: root
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./nginx}/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lcpserver
      - lsdserver
      - frontend
    networks:
      - app-network

  lcpserver:
    build:
      context: ../  # Path to your Dockerfile
      dockerfile: ci/Dockerfile
      target: runtime-lcp
    image: local/lcpserver:latest
    volumes:
        - ./data/files/storage:/data/files/storage
        - ./data/files/encrypted:/data/files/encrypted
    user: root  # Add this line
    ports:
      - "8989:8989"
    networks:
      - app-network

  lsdserver:
    build:
      context: ../  # Path to your Dockerfile
      dockerfile: ci/Dockerfile
      target: runtime-lsd
    image: local/lsdserver:latest
    volumes:
        - ./data/files/storage:/data/files/storage
        - ./data/files/encrypted:/data/files/encrypted
    user: root  # Add this line
    ports:
      - "8990:8990"
    networks:
      - app-network

  frontend:
    build:
      context: ../  # Path to your Dockerfile
      dockerfile: ci/Dockerfile
      target: runtime-frontend
    image: local/frontend:latest
    volumes:
        - ./data/files/storage:/data/files/storage
        - ./data/files/encrypted:/data/files/encrypted
    user: root  # Add this line
    ports:
      - "8991:8991"  # Adjust ports as needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
