version: '3.8'

services:
  nginx:
    image: nginx:latest  # Använd den offentliga nginx-bilden från Docker Hub
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lcpserver
      - lsdserver

  lcpserver:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ci/Dockerfile
      target: runtime-lcp
    image: ghcr.io/notalib/readium-lcp-server/lcpserver:${TAG}
    #environment:
    #volumes:
      # i18n ?
    ports:
      - 8989:8989
    networks:
      - app-network

  lsdserver:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ci/Dockerfile
      target: runtime-lsd
    image: ghcr.io/notalib/readium-lcp-server/lsdserver:${TAG}
    #environment:
    #volumes:
      # i18n ?
    ports:
      - 8990:8990
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
