version: '3.8'

services:
  nginx:
    image: nginx:latest  # Använd den offentliga nginx-bilden från Docker Hub
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lcpserver
      - lsdserver

  lcpserver:
    restart: unless-stopped
    image: lcslsdcontainer.azurecr.io/lcpserver:${TAG}
    ports:
      - "8989:8989"
    networks:
      - app-network

  lsdserver:
    restart: unless-stopped
    image: lcslsdcontainer.azurecr.io/lsdserver:${TAG}
    ports:
      - "8990:8990"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
