version: '3.8'

services:
  nginx:
    image: lcslsdcontainer.azurecr.io/nginx:latest  # Din egen Nginx-image med nginx.conf inkluderad
    ports:
      - "80:80"
    depends_on:
      - lcpserver
      - lsdserver
    networks:
      - app-network

  lcpserver:
    restart: unless-stopped
    image: lcslsdcontainer.azurecr.io/lcpserver:latest
    ports:
      - "8989:8989"
    networks:
      - app-network

  lsdserver:
    restart: unless-stopped
    image: lcslsdcontainer.azurecr.io/lsdserver:latest
    ports:
      - "8990:8990"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
